/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellFinancasRouteImport } from './routes/_shell.financas'
import { Route as ShellCartoesRouteImport } from './routes/_shell.cartoes'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinancasRoute = ShellFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCartoesRoute = ShellCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/cartoes': typeof ShellCartoesRoute
  '/financas': typeof ShellFinancasRoute
}
export interface FileRoutesByTo {
  '/cartoes': typeof ShellCartoesRoute
  '/financas': typeof ShellFinancasRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/cartoes': typeof ShellCartoesRoute
  '/_shell/financas': typeof ShellFinancasRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cartoes' | '/financas'
  fileRoutesByTo: FileRoutesByTo
  to: '/cartoes' | '/financas' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/cartoes'
    | '/_shell/financas'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/financas': {
      id: '/_shell/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof ShellFinancasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cartoes': {
      id: '/_shell/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof ShellCartoesRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCartoesRoute: typeof ShellCartoesRoute
  ShellFinancasRoute: typeof ShellFinancasRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCartoesRoute: ShellCartoesRoute,
  ShellFinancasRoute: ShellFinancasRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
